enum WalletType {
  SAFE
  BICONOMY
}

input WalletFeature {
  id: String!
  serializedParams: String!
}

type CreateWalletFromMetadataResponse {
  status: Int!
}

type Mutation {
  createWalletFromMetadata(
    walletType: WalletType!
    features: [WalletFeature!]!
  ): CreateWalletFromMetadataResponse!
}

type Query {
  ping: String!
}
