enum WalletType {
  SAFE
  BICONOMY
}

type Query {
  ping: String!
}

type UserWalletsMeta {
  companyName: String!
  minaSmartContractAddress: String!
  walletType: WalletType!
}

type UserWalletsMetaResponse {
  data: UserWalletsMeta
  status: Int!
}

type Query {
  getUserWalletsMeta(cid: String!): UserWalletsMetaResponse!
}

input SaveUserWalletsMetaInput {
  companyName: String!
  minaSmartContractAddress: String!
  walletType: WalletType!
}

type SaveUserWalletsMetaResponse {
  cid: String
  status: Int!
}

type Mutation {
  saveUserWalletsMeta(
    input: SaveUserWalletsMetaInput!
  ): SaveUserWalletsMetaResponse!
}
